config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :jobs
  resource :favorites
  root 'welcome#index'

  get 'welcome/about'

end

app/models/job.rb
class Job < ActiveRecord::Base

  self.primary_key = 'al_job_id'

  belongs_to :location, foreign_key: 'al_loc_id'
  belongs_to :startup, foreign_key: 'al_start_id'

  has_and_belongs_to_many :users, foreign_key: 'al_job_id'

  validates :al_start_id, uniqueness: true

end

app/models/location.rb
class Location < ActiveRecord::Base

  self.primary_key = 'al_loc_id'

  has_many :jobs, foreign_key: 'al_loc_id'
  has_many :startups, foreign_key: 'al_loc_id'
  has_one :zillow, foreign_key: 'al_loc_id'

  validates :al_loc_id, uniqueness: true

  geocoded_by :address
  
  reverse_geocoded_by :latitude, :longitude do |obj,results|
    if geo = results.first
      obj.city = geo.city
      obj.state = geo.state_code
      obj.zipcode = geo.postal_code
    end
  end

  after_validation :geocode, :reverse_geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

end

app/models/startup.rb
class Startup < ActiveRecord::Base

  self.primary_key = 'al_start_id'

  belongs_to :location, foreign_key: 'al_loc_id'
  has_many :jobs, foreign_key: 'al_start_id'

  validates :al_start_id, uniqueness: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :jobs, association_foreign_key: 'al_job_id'
end

app/models/zillow.rb
class Zillow < ActiveRecord::Base

  self.primary_key = 'al_loc_id'

  belongs_to :location, foreign_key: 'al_loc_id'

  validates :al_loc_id, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/favorite_jobs_controller.rb
class FavoriteJobsController < ApplicationController

  # before_action :set_job

  def create
    @job = Job.find(params[:id])
    if Favorite.create(favorited: @job, user: current_user)
      redirect_to @job, notice: 'Job has been favorited'
    else
      redirect_to @job, alert: 'Something went wrong...*sad panda*'
    end
  end

  def destroy
    Favorite.where(favorited_id: @job.id, user_id: current_user.id).first.destroy
    redirect_to @job, notice: 'Job is no longer in favorites'
  end

  # private

  # def set_job
  #   @job = Job.find(params[:job_id])
  # end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def show
    @favorites = current_user.jobs.paginate(:page => params[:page], :per_page => 6)
  end

  def create
     @job = Job.find(params[:id])
    if current_user.jobs<<(@job)
      redirect_to jobs_url(search: params[:search]), notice: 'Job has been favorited'
    else
      redirect_to jobs_url(search: params[:search]), notice: 'Something went wrong...*sad panda*'
    end
  end

  def destroy
    @favorites = current_user.jobs
    @job = Job.find(params[:id])
    @favorites.destroy(@job)
    redirect_to favorites_url, notice: 'Job has been removed from your favorites list.'
  end


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def show
    @location = Location.find_by(address: params[:search].downcase)
      @hash = Gmaps4rails.build_markers(@location) do |location, marker|
        marker.lat location.latitude
        marker.lng location.longitude
      end

    if @location 
      @jobs = @location.jobs.paginate(:page => params[:page], :per_page => 6) 
      @zillow = @location.zillow
    else
      flash[:notice] = "No Startups were found in #{params[:search]}. Please try your search again."
      redirect_to(:back)
    end
   
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @jobs = Job.find_by_al_loc_id
    @user = User.find_by_id
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorite_jobs_helper.rb
module FavoriteJobsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/favorites/show.html.erb
<div class="container">
  <div class="favorite-title">
    <h1>Favorites</h1>
  </div>
  <% @favorites.each do |fav| %>
      <%= link_to image_tag(fav.startup.thumb_url), "#{fav.startup.url}", target: "_blank", class: "thumbnail" %>
      <ul class="startup-list">
        <li><h2 class="h2-li"><%= fav.startup.name %> <span CLASS="title-h2">(<%= fav.location.display_name %>/<%= fav.job_type.titleize %>)</span></h2></li>
        <li><strong>Job title:</strong> <%= fav.title.truncate_words(10) %></li>
        <% if fav.salary_max && fav.salary_min != nil && fav.salary_max && fav.salary_min != 0 %>
          <li><strong>Salary: </strong>$<%= number_with_delimiter(fav.salary_min, delimiter: ',') %> - $<%= number_with_delimiter(fav.salary_max, delimiter: ',') %></li>
        <% else %>
          <li><strong>Salary: </strong>N/A</li>
        <% end %>
        <li>
          <%= link_to "Details", fav.al_url %> | 
          <%= link_to "Website", fav.startup.url, target: "_blank" %> |
          <%= form_tag(favorites_path, method: 'delete') do %>
            <%= hidden_field_tag(:id, fav.id) %>
            <%= button_tag(type: 'Delete', class: "btn btn-sm btn-primary") do %>
              <span><i class="fa fa-times"></i></span> Remove
            <% end %>
          <% end %>
        </li>
      </ul>
    <hr>
  <% end %>

  <div class="back">
    <%= link_to "Back", url_for(:back), class: "btn btn-default" %>
  </div>

  <%= will_paginate @favorites, renderer: BootstrapPagination::Rails %>

</div>

app/views/jobs/_jobs.html.erb
<% @jobs.each do |job| %>
    <%= link_to image_tag(job.startup.thumb_url), "#{job.startup.url}", target: "_blank", class: "thumbnail" %>
    <ul class="startup-list">
      <li><h2 class="h2-li"><%= job.startup.name %> <span CLASS="title-h2">(<%= job.job_type.titleize %>)</span></h2></li>
      <li><strong>Job title:</strong> <%= job.title.truncate_words(10) %></li>
      <% if job.salary_max && job.salary_min != nil && job.salary_max && job.salary_min != 0 %>
        <li><strong>Salary: </strong>$<%= number_with_delimiter(job.salary_min, delimiter: ',') %> - $<%= number_with_delimiter(job.salary_max, delimiter: ',') %></li>
      <% else %>
        <li><strong>Salary: </strong>N/A</li>
      <% end %>
      <li>
        <%= link_to "Details", job.al_url %> | 
        <%= link_to "Website", job.startup.url %> |
          <% if current_user %>
            <% if current_user.jobs.exists?(al_job_id: job.al_job_id) %>
            <span><i class="fa fa-star"></i></span>
            <% else %>
              <%= form_tag(favorites_path) do %>
                <%= hidden_field_tag(:id, job.id) %>
                <%= hidden_field_tag(:search, params[:search]) %>
                <%= button_tag(type: 'submit', class: "btn btn-default") do %>
                  <span><i class="fa fa-thumb-tack"></i></span> 
                <% end %>
              <% end %>
            <% end %>
            <% else %>
              <%= form_tag(favorites_path) do %>
                <%= hidden_field_tag(:id, job.id) %>
                <%= hidden_field_tag(:search, params[:search]) %>
                <%= button_tag(type: 'submit', class: "btn btn-default") do %>
                  <span><i class="fa fa-thumb-tack"></i></span> 
                <% end %>
              <% end %>
          <% end %>
      </li>
    </ul>
  <hr>
<% end %>

app/views/jobs/_maps.html.erb
<div id="map" class="map_container">
  <script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {maxZoom: 10}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
  </script>
</div>
<%= form_tag jobs_path, :method => :get do %>
<div class="pull-right">
  <div class="input-group input-group-md">
    <%= text_field_tag :search, params[:search].downcase, placeholder: "search by city", class: "form-control" %>
      <span class="input-group-btn"><%= submit_tag "Search", name: nil, class: "btn btn-default" %></span>
    <% end %>
  </div>

app/views/jobs/_no_zillow_data.html.erb
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
           Economic & Transportation Info 
          </a>
        </h4>
      </div>
      <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
        <ul class="list-group">
          <li><strong>Median Household income:</strong> No data available </li> 
          <li><strong>Home Value Index:</strong> No data available </li>
          <li><strong>Average Commute Time:</strong> No data available </li>
        </ul>
      </div>
    </div>
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="headingTwo">
            <h4 class="panel-title">
                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                 City Characteristics 
                </a>
            </h4>
          </div>
          <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
            <ul class="list-group">
              <li class="culter"><strong>Education:</strong> No data available </li>
              <li class="culter"><strong>People & Culture:</strong> No data available </li>
              <li class="culter"><strong>Transportation:</strong> No data available </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

app/views/jobs/_zillow_data.html.erb
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
           Economic & Transportation Info 
          </a>
        </h4>
      </div>
      <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
        <ul class="list-group">
          <li><strong>Median Household income:</strong> $<%= number_with_delimiter(@zillow.med_house_income, delimiter: ',') %></li> 
          <li class="nat-avg" style="
    font-size: .9em;">(National average $<%= number_with_delimiter(@zillow.med_nat_house_income, delimiter: ',') %>)</li>
          <li><strong>Home Value Index:</strong> $<%= number_with_delimiter(@zillow.zillow_HVI, delimiter: ',') %></li>
          <li class="nat-avg" style="
    font-size: .9em;">(National average $<%= number_with_delimiter(@zillow.zillow_nat_HVI, delimiter: ',') %>)</li>
          <li><strong>Average Commute Time:</strong> About <%= @zillow.avg_commute_time.round %> minutes</li>
          <li class="nat-avg" style="
    font-size: .9em;">(National average About <%= @zillow.avg_nat_commute_time.round %> minutes)</li>
        </ul>
      </div>
    </div>
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="headingTwo">
            <h4 class="panel-title">
                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                 City Characteristics 
                </a>
            </h4>
          </div>
          <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
            <ul class="list-group">
              <li class="culter"><strong>Education:</strong> <%= @zillow.education %></li>
              <li class="culter"><strong>People & Culture:</strong> <%= @zillow.people_culture %></li>
              <li class="culter"><strong>Transportation:</strong> <%= @zillow.transportation %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  

app/views/jobs/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>

<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<div class="container">
  <div class="panel-body col-md-4 pull-right">
    <%= render 'maps' %>
    <% if @zillow %>
      <%= render 'zillow_data' %>
    <% else %>
      <%= render 'no_zillow_data' %>
    <% end %>
  </div>
  
  <div class="h1-title">
    <h1>Startups in <%= @location.display_name %></h1>
  </div>
  
  <div class="col-md-8">

    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <%= render 'jobs' %>

    <%= will_paginate @jobs, renderer: BootstrapPagination::Rails %>

  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <p style="text-align:center;">NewStart &copy <%= Time.new.year %></p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
      <i class="fa fa-leaf"> </i><%= link_to 'NewStart', root_path %>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%=link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to favorites_path do %>
                  <span class="glyphicon glyphicon-star"></span> Favorites
              <% end %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign Up', new_user_registration_path %></a></li>
            <li><%= link_to 'Sign In', user_session_path %></li>
            <% end %>
        </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewStart</title>
  <link href='http://fonts.googleapis.com/css?family=Josefin+Slab|Open+Sans+Condensed:300,300italic|Kaushan+Script|Francois+One|Raleway' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/header' %>
</head>
<body>

<div class="container"> 
 <% if flash[:error] %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
 </div> 
 
<%= yield %>

</body>
  <%= render 'layouts/footer' %>
</html>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div id="overlay">
    <h1 style="text-align:center;">Ready for a new start?</h1>
      <p style="text-align:center;">Search thousands of startups from all across the U.S.</p>
        <%= form_tag jobs_path, :method => :get do %>
          <div class="col-md-6 col-md-offset-3">
            <div class="input-group input-group-lg">
              <%= text_field_tag :search, params[:search], placeholder: "search by city", class: "form-control" %>
              <span class="input-group-btn"><%= submit_tag "Search", name: nil, class: "btn btn-default" %></span>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="about">
  <div class="container homepage">
    <h2>ABOUT NEWSTART</h2>
    <hr>
    <p>Looking for a spark in your career?  Want to move to a fresh scene?  
We developed <span class="new-start">NewStart</span> to help you locate a fun position at a young company in a city that best suits your lifestyle.  

Start by searching for a city that peaks your interest.  From there you will be presented with a list of the job opportunities that are available in that area.  Along side the job posting, you will find a map, economic & traffic information as well as characteristics of the city.

We also offer the ability to create an account with us to save job postings that you are interested in.</p>
  </div>
</div>

<div id="how-it-works">
  <div class="container homepage">
      <h2>HOW IT WORKS</h2>
      <hr>
    <div class="row">
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-angellist fa-stack-1x fa-inverse"></i>
        </span>
          <h3>AngelList</h3>
          <p>The AngelList API allows the user to search startup jobs from all across the United States.  </p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-map-marker fa-stack-1x fa-inverse"></i>
        </span>
          <h3>Google Maps</h3>
          <p>By using the Google maps API our users are able to quickly visualize the location of the city they are searching. </p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-bar-chart fa-stack-1x fa-inverse"></i>
        </span>
          <h3>City Data</h3>
          <p>The Zillow API allows the user to view a snapshot of economic, transportation and cultural data. </p>
      </div>
    </div>
  </div> <!-- /container -->
</div>